error in yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,4 +13,4 @@ jobs:
        run: echo "This workflow runs successfully for this action."
        
      - name: Simulating error
-       run: echo "Error message" exit 1
+       run: echo "Error message"; exit 1
