Adding erro in yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,3 +11,6 @@ jobs:
      
      - name: Run a sample github action
        run: echo "This workflow runs successfully for this action."
+       
+     - name: Simulating error
+       run: echo "Error message" exit 1
