Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,5 +12,5 @@ jobs:
      - name: Run a sample github action
        run: echo "This workflow runs successfully for this action."
        
-     - name: Simulating error
-       run: echo "Error message"; exit 1
+ #    - name: Simulating error
+ #      run: echo "Error message"; exit 1
